let names = [
  {
    foto: "Default",
    name: "Default user",
    lname: "Default",
    email: "Default",
    mobile: "Default",
    city: "Default",
    group: "Prive",
    hasSocial: ['Facebook'],
    socialNetworks: ['Facebook','Twitter','SnapChat'],
    groups: ["Prive","Zakelijk","Vriend","Familie"],
  },
  {
    foto: "Default",
    name: "Default user",
    lname: "Default",
    email: "Default",
    mobile: "Default",
    city: "Default",
    group: "Prive",
    hasSocial: ['Facebook'],
    socialNetworks: ['Facebook','Twitter','SnapChat'],
    groups: ["Prive","Zakelijk","Vriend","Familie"],
  },
  {
    foto: "Default",
    name: "Default user",
    lname: "Default",
    email: "Default",
    mobile: "Default",
    city: "Default",
    group: "Prive",
    hasSocial: ['Facebook'],
    socialNetworks: ['Facebook','Twitter','SnapChat'],
    groups: ["Prive","Zakelijk","Vriend","Familie"],
  },
];
